#ifndef UNITY_CONFIG_H
#define UNITY_CONFIG_H

#define UNITY_FIXTURE_NO_EXTRAS

#define UNITY_EXCLUDE_FLOAT
#define UNITY_INCLUDE_DOUBLE
#define UNITY_DOUBLE_PRECISION 1e-12

#endif /* UNITY_CONFIG_H */
